import { z } from "zod";

export const ukPage0Schema = z.object({
  system_name: z.string().min(1, "System name is required"),
  description: z.string().min(1, "Description is required"),
  owner: z.string().optional(),
  jurisdiction: z.string().optional(),
  sector: z.string().min(1, "Sector is required"),
  system_status: z.string().optional(),
  business_use_case: z.string().optional(),
});

export const ukPage1Schema = z.object({
  robustness_testing: z.boolean().optional(),
  robustness_testing_methods: z.string().optional(),
  robustness_testing_frequency_text: z.string().optional(),
  robustness_test_results: z.string().optional(),
  red_teaming: z.boolean().optional(),
  red_teaming_who: z.string().optional(),
  red_teaming_methodology: z.string().optional(),
  red_teaming_findings: z.string().optional(),
  misuse_prevention: z.boolean().optional(),
  misuse_prevention_measures: z.string().optional(),
  misuse_monitoring: z.string().optional(),
  cybersecurity: z.boolean().optional(),
  cybersecurity_controls: z.string().optional(),
  cybersecurity_incident_response: z.string().optional(),
  cybersecurity_monitoring: z.string().optional(),
  safety_testing: z.boolean().optional(),
  safety_testing_protocols: z.string().optional(),
  safety_validation_methods: z.string().optional(),
});

export const ukPage2Schema = z.object({
  user_disclosure: z.boolean().optional(),
  user_disclosure_how: z.string().optional(),
  user_disclosure_when: z.string().optional(),
  user_disclosure_format: z.string().optional(),
  explainability: z.boolean().optional(),
  explainability_methods: z.string().optional(),
  explainability_technical_details: z.string().optional(),
  explainability_user_types: z.string().optional(),
  documentation: z.boolean().optional(),
  documentation_types: z.string().optional(),
  documentation_storage: z.string().optional(),
  documentation_update_frequency: z.string().optional(),
  transparency_reports: z.boolean().optional(),
  transparency_reports_content: z.string().optional(),
  transparency_reports_frequency: z.string().optional(),
  transparency_reports_publication: z.string().optional(),
});

export const ukPage3Schema = z.object({
  bias_testing: z.boolean().optional(),
  bias_testing_methodology: z.string().optional(),
  bias_testing_tools: z.string().optional(),
  bias_testing_frequency: z.string().optional(),
  bias_testing_results: z.string().optional(),
  discrimination_mitigation: z.boolean().optional(),
  discrimination_mitigation_measures: z.string().optional(),
  data_quality: z.boolean().optional(),
  data_quality_checks: z.string().optional(),
  data_quality_metrics: z.string().optional(),
  fairness_monitoring: z.boolean().optional(),
  fairness_monitoring_processes: z.string().optional(),
  fairness_monitoring_alerts: z.string().optional(),
  personal_data_handling: z.boolean().optional(),
  personal_data_types: z.string().optional(),
  personal_data_sources: z.string().optional(),
  personal_data_retention: z.string().optional(),
  data_representativeness: z.string().optional(),
  protected_characteristics: z.string().optional(),
  fairness_metrics_used: z.string().optional(),
});

export const ukPage4Schema = z.object({
  accountability_framework: z.boolean().optional(),
  accountability_framework_structure: z.string().optional(),
  accountability_roles: z.string().optional(),
  human_oversight: z.boolean().optional(),
  human_oversight_who: z.string().optional(),
  human_oversight_when: z.string().optional(),
  human_oversight_how: z.string().optional(),
  risk_management: z.boolean().optional(),
  risk_management_processes: z.string().optional(),
  risk_management_documentation: z.string().optional(),
  governance_structure: z.boolean().optional(),
  governance_board_involvement: z.string().optional(),
  governance_committees: z.string().optional(),
  audit_trail: z.boolean().optional(),
  audit_trail_what: z.string().optional(),
  audit_trail_retention: z.string().optional(),
  audit_trail_access: z.string().optional(),
  senior_management_oversight: z.string().optional(),
  ethics_committee: z.boolean().optional(),
  ethics_committee_details: z.string().optional(),
  policy_assignment: z.string().optional(),
  training_requirements: z.string().optional(),
  escalation_procedures: z.string().optional(),
  accountable_person: z.string().min(1, "Accountable person is required"),
});

export const ukPage5Schema = z.object({
  user_rights: z.boolean().optional(),
  user_rights_what: z.string().optional(),
  user_rights_communication: z.string().optional(),
  appeal_mechanism: z.boolean().optional(),
  appeal_mechanism_process: z.string().optional(),
  appeal_mechanism_timeline: z.string().optional(),
  appeal_mechanism_accessibility: z.string().optional(),
  redress_process: z.boolean().optional(),
  redress_process_steps: z.string().optional(),
  redress_compensation: z.string().optional(),
  redress_documentation: z.string().optional(),
  complaint_handling: z.boolean().optional(),
  complaint_handling_procedures: z.string().optional(),
  complaint_response_time: z.string().optional(),
  complaint_tracking: z.string().optional(),
  appeal_success_rates: z.string().optional(),
  redress_outcomes_tracking: z.string().optional(),
});

export const ukPage6Schema = z.object({
  foundation_model: z.enum(["yes", "no", "unsure"]).optional(),
  foundation_model_cards: z.boolean().optional(),
  foundation_model_documentation: z.string().optional(),
  foundation_model_capability_testing: z.string().optional(),
  foundation_model_risk_assessment: z.string().optional(),
  foundation_model_deployment_restrictions: z.string().optional(),
  foundation_model_monitoring: z.string().optional(),
  regulatory_sandbox: z.boolean().optional(),
  regulatory_sandbox_details: z.string().optional(),
  sector_specific_requirements: z.string().optional(),
});

export const ukComprehensiveSchema = ukPage0Schema
  .merge(ukPage1Schema)
  .merge(ukPage2Schema)
  .merge(ukPage3Schema)
  .merge(ukPage4Schema)
  .merge(ukPage5Schema)
  .merge(ukPage6Schema);

export const ukRapidSchema = ukPage0Schema
  .merge(z.object({
    robustness_testing: z.boolean().optional(),
    personal_data_handling: z.boolean().optional(),
    human_oversight: z.boolean().optional(),
    accountability_framework: z.boolean().optional(),
    foundation_model: z.enum(["yes", "no", "unsure"]).optional(),
    regulatory_sandbox: z.boolean().optional(),
    regulatory_sandbox_details: z.string().optional(),
    sector_specific_requirements: z.string().optional(),
  }));

export type UkFormValues = z.infer<typeof ukComprehensiveSchema>;

export const ukPageSchemas = [
  ukPage0Schema,
  ukPage1Schema,
  ukPage2Schema,
  ukPage3Schema,
  ukPage4Schema,
  ukPage5Schema,
  ukPage6Schema,
];

export const ukRapidPageSchemas = [
  ukPage0Schema,
  z.object({
    robustness_testing: z.boolean().optional(),
    personal_data_handling: z.boolean().optional(),
    human_oversight: z.boolean().optional(),
    accountability_framework: z.boolean().optional(),
  }),
  ukPage6Schema,
];

export function getDefaultValues(existingData?: Partial<UkFormValues>): UkFormValues {
  return {
    system_name: existingData?.system_name || "",
    description: existingData?.description || "",
    owner: existingData?.owner || "",
    jurisdiction: existingData?.jurisdiction || "",
    sector: existingData?.sector || "",
    system_status: existingData?.system_status || "envision",
    business_use_case: existingData?.business_use_case || "",
    robustness_testing: existingData?.robustness_testing || false,
    robustness_testing_methods: existingData?.robustness_testing_methods || "",
    robustness_testing_frequency_text: existingData?.robustness_testing_frequency_text || "",
    robustness_test_results: existingData?.robustness_test_results || "",
    red_teaming: existingData?.red_teaming || false,
    red_teaming_who: existingData?.red_teaming_who || "",
    red_teaming_methodology: existingData?.red_teaming_methodology || "",
    red_teaming_findings: existingData?.red_teaming_findings || "",
    misuse_prevention: existingData?.misuse_prevention || false,
    misuse_prevention_measures: existingData?.misuse_prevention_measures || "",
    misuse_monitoring: existingData?.misuse_monitoring || "",
    cybersecurity: existingData?.cybersecurity || false,
    cybersecurity_controls: existingData?.cybersecurity_controls || "",
    cybersecurity_incident_response: existingData?.cybersecurity_incident_response || "",
    cybersecurity_monitoring: existingData?.cybersecurity_monitoring || "",
    safety_testing: existingData?.safety_testing || false,
    safety_testing_protocols: existingData?.safety_testing_protocols || "",
    safety_validation_methods: existingData?.safety_validation_methods || "",
    user_disclosure: existingData?.user_disclosure || false,
    user_disclosure_how: existingData?.user_disclosure_how || "",
    user_disclosure_when: existingData?.user_disclosure_when || "",
    user_disclosure_format: existingData?.user_disclosure_format || "",
    explainability: existingData?.explainability || false,
    explainability_methods: existingData?.explainability_methods || "",
    explainability_technical_details: existingData?.explainability_technical_details || "",
    explainability_user_types: existingData?.explainability_user_types || "",
    documentation: existingData?.documentation || false,
    documentation_types: existingData?.documentation_types || "",
    documentation_storage: existingData?.documentation_storage || "",
    documentation_update_frequency: existingData?.documentation_update_frequency || "",
    transparency_reports: existingData?.transparency_reports || false,
    transparency_reports_content: existingData?.transparency_reports_content || "",
    transparency_reports_frequency: existingData?.transparency_reports_frequency || "",
    transparency_reports_publication: existingData?.transparency_reports_publication || "",
    bias_testing: existingData?.bias_testing || false,
    bias_testing_methodology: existingData?.bias_testing_methodology || "",
    bias_testing_tools: existingData?.bias_testing_tools || "",
    bias_testing_frequency: existingData?.bias_testing_frequency || "",
    bias_testing_results: existingData?.bias_testing_results || "",
    discrimination_mitigation: existingData?.discrimination_mitigation || false,
    discrimination_mitigation_measures: existingData?.discrimination_mitigation_measures || "",
    data_quality: existingData?.data_quality || false,
    data_quality_checks: existingData?.data_quality_checks || "",
    data_quality_metrics: existingData?.data_quality_metrics || "",
    fairness_monitoring: existingData?.fairness_monitoring || false,
    fairness_monitoring_processes: existingData?.fairness_monitoring_processes || "",
    fairness_monitoring_alerts: existingData?.fairness_monitoring_alerts || "",
    personal_data_handling: existingData?.personal_data_handling || false,
    personal_data_types: existingData?.personal_data_types || "",
    personal_data_sources: existingData?.personal_data_sources || "",
    personal_data_retention: existingData?.personal_data_retention || "",
    data_representativeness: existingData?.data_representativeness || "",
    protected_characteristics: existingData?.protected_characteristics || "",
    fairness_metrics_used: existingData?.fairness_metrics_used || "",
    accountability_framework: existingData?.accountability_framework || false,
    accountability_framework_structure: existingData?.accountability_framework_structure || "",
    accountability_roles: existingData?.accountability_roles || "",
    human_oversight: existingData?.human_oversight || false,
    human_oversight_who: existingData?.human_oversight_who || "",
    human_oversight_when: existingData?.human_oversight_when || "",
    human_oversight_how: existingData?.human_oversight_how || "",
    risk_management: existingData?.risk_management || false,
    risk_management_processes: existingData?.risk_management_processes || "",
    risk_management_documentation: existingData?.risk_management_documentation || "",
    governance_structure: existingData?.governance_structure || false,
    governance_board_involvement: existingData?.governance_board_involvement || "",
    governance_committees: existingData?.governance_committees || "",
    audit_trail: existingData?.audit_trail || false,
    audit_trail_what: existingData?.audit_trail_what || "",
    audit_trail_retention: existingData?.audit_trail_retention || "",
    audit_trail_access: existingData?.audit_trail_access || "",
    senior_management_oversight: existingData?.senior_management_oversight || "",
    ethics_committee: existingData?.ethics_committee || false,
    ethics_committee_details: existingData?.ethics_committee_details || "",
    policy_assignment: existingData?.policy_assignment || "",
    training_requirements: existingData?.training_requirements || "",
    escalation_procedures: existingData?.escalation_procedures || "",
    accountable_person: existingData?.accountable_person || "",
    user_rights: existingData?.user_rights || false,
    user_rights_what: existingData?.user_rights_what || "",
    user_rights_communication: existingData?.user_rights_communication || "",
    appeal_mechanism: existingData?.appeal_mechanism || false,
    appeal_mechanism_process: existingData?.appeal_mechanism_process || "",
    appeal_mechanism_timeline: existingData?.appeal_mechanism_timeline || "",
    appeal_mechanism_accessibility: existingData?.appeal_mechanism_accessibility || "",
    redress_process: existingData?.redress_process || false,
    redress_process_steps: existingData?.redress_process_steps || "",
    redress_compensation: existingData?.redress_compensation || "",
    redress_documentation: existingData?.redress_documentation || "",
    complaint_handling: existingData?.complaint_handling || false,
    complaint_handling_procedures: existingData?.complaint_handling_procedures || "",
    complaint_response_time: existingData?.complaint_response_time || "",
    complaint_tracking: existingData?.complaint_tracking || "",
    appeal_success_rates: existingData?.appeal_success_rates || "",
    redress_outcomes_tracking: existingData?.redress_outcomes_tracking || "",
    foundation_model: existingData?.foundation_model || "no",
    foundation_model_cards: existingData?.foundation_model_cards || false,
    foundation_model_documentation: existingData?.foundation_model_documentation || "",
    foundation_model_capability_testing: existingData?.foundation_model_capability_testing || "",
    foundation_model_risk_assessment: existingData?.foundation_model_risk_assessment || "",
    foundation_model_deployment_restrictions: existingData?.foundation_model_deployment_restrictions || "",
    foundation_model_monitoring: existingData?.foundation_model_monitoring || "",
    regulatory_sandbox: existingData?.regulatory_sandbox || false,
    regulatory_sandbox_details: existingData?.regulatory_sandbox_details || "",
    sector_specific_requirements: existingData?.sector_specific_requirements || "",
  };
}
